import { GPU } from "./RawDataInterfaces";

export const gpus: GPU[] = [
    {
        manufacturer: "ASUS",
        model: "ROG Strix GeForce RTX 4090 OC",
        price: 1998.34,
        powerRequirement: 450,
        memory: 24,
        computeUnits: 86,
        pcieRequirement: 4.0,
    },
    {
        manufacturer: "MSI",
        model: "GeForce RTX 3060 Ventus 2X 12G OC",
        price: 299.80,
        powerRequirement: 170,
        memory: 12,
        computeUnits: 13,
        pcieRequirement: 4.0,
    },
    {
        manufacturer: "ASUS",
        model: "NVIDIA GeForce GT 710",
        price: 53.80,
        powerRequirement: 19,
        memory: 2,
        computeUnits: 0.2,
        pcieRequirement: 2.0,
    },
    {
        manufacturer: "Intel",
        model: "Arc A750 Graphics",
        price: 293.80,
        powerRequirement: 225,
        memory: 8,
        computeUnits: 30,
        pcieRequirement: 4.0,
    },
    {
        manufacturer: "GIGABYTE",
        model: "GeForce RTX 3050 Eagle",
        price: 260.80,
        powerRequirement: 130,
        memory: 8,
        computeUnits: 9,
        pcieRequirement: 4.0,
    },
    {
        manufacturer: "GIGABYTE",
        model: "GeForce RTX 3060 Ti Eagle",
        price: 337.80,
        powerRequirement: 200,
        memory: 8,
        computeUnits: 16,
        pcieRequirement: 4.0,
    },
    {
        manufacturer: "GIGABYTE",
        model: "GeForce RTX 2070 SUPER Gaming OC",
        price: 698.80,
        powerRequirement: 220,
        memory: 8,
        computeUnits: 19,
        pcieRequirement: 3.0,
    },
    {
        manufacturer: "MSI",
        model: "GeForce RTX 4070 Gaming X Trio",
        price: 733.80,
        powerRequirement: 260,
        memory: 12,
        computeUnits: 30,
        pcieRequirement: 4.0,
    },
    {
        manufacturer: "ASUS",
        model: "TUF Gaming GeForce RTX 4080 OC",
        price: 1325.80,
        powerRequirement: 320,
        memory: 16,
        computeUnits: 51,
        pcieRequirement: 4.0,
    },
    {
        manufacturer: "GIGABYTE",
        model: "GeForce RTX 3070 Ventus 3X 8G OC LHR",
        price: 599.80,
        powerRequirement: 220,
        memory: 8,
        computeUnits: 20,
        pcieRequirement: 4.0,
    },
    {
        manufacturer: "ASUS",
        model: "TUF Gaming GeForce RTX 3080 OC V2 (LHR)",
        price: 842.80,
        powerRequirement: 320,
        memory: 10,
        computeUnits: 31,
        pcieRequirement: 4.0,
    },
    {
        manufacturer: "MSI",
        model: "GeForce RTX 3080 Suprim X 10G LHR",
        price: 789.80,
        powerRequirement: 320,
        memory: 10,
        computeUnits: 33,
        pcieRequirement: 4.0,
    },
    {
        manufacturer: "MSI",
        model: "GeForce RTX 3080 Suprim X 10G LHR",
        price: 789.80,
        powerRequirement: 320,
        memory: 10,
        computeUnits: 33,
        pcieRequirement: 4.0,
    },
    {
        manufacturer: "ASUS",
        model: "Dual GeForce RTX 2080 Advanced",
        price: 849.80,
        powerRequirement: 320,
        memory: 8,
        computeUnits: 20,
        pcieRequirement: 3.0,
    },
    {
        manufacturer: "ASUS",
        model: "ROG Strix GeForce RTX 3090 OC White",
        price: 2100.80,
        powerRequirement: 350,
        memory: 24,
        computeUnits: 40,
        pcieRequirement: 4.0,
    },
]