import { Motherboard } from "./RawDataInterfaces";

export const motherboards: Motherboard[] = [
    {
        manufacturer: "ASUS",
        model: "ROG Strix Z590-E Gaming",
        price: 399.99,
        socket: "LGA1200",
        ramSlots: 4,
        ramType: "DDR4",
        pcieSlots: 3,
        pcieRequirement: 4.0,
        sataSlots: 6,
        usbPorts: 12,
        powerRequirement: 170,
    },
    {
        manufacturer: "MSI",
        model: "MPG B550 GAMING PLUS",
        price: 117.90,
        socket: "AM4",
        ramSlots: 4,
        ramType: "DDR4",
        pcieSlots: 3,
        pcieRequirement: 4.0,
        sataSlots: 6,
        usbPorts: 8,
        powerRequirement: 135,
    },
    {
        manufacturer: "GIGABYTE",
        model: "B550 GAMING X V2",
        price: 123.90,
        socket: "AM4",
        ramSlots: 4,
        ramType: "DDR4",
        pcieSlots: 5,
        pcieRequirement: 2.0,
        sataSlots: 4,
        usbPorts: 6,
        powerRequirement: 135,
    },
    {
        manufacturer: "MSI",
        model: "MPG Z790 CARBON WIFI",
        price: 408.90,
        socket: "LGA1700",
        ramSlots: 4,
        ramType: "DDR5",
        pcieSlots: 7,
        pcieRequirement: 3.0,
        sataSlots: 6,
        usbPorts: 13,
        powerRequirement: 160,
    },
    {
        manufacturer: "ASUS",
        model: "Pro WS WRX80E-Sage SE WIFI II",
        price: 942.90,
        socket: "sWRX8",
        ramSlots: 8,
        ramType: "DDR4",
        pcieSlots: 10,
        pcieRequirement: 4.0,
        sataSlots: 8,
        usbPorts: 7,
        powerRequirement: 280,
    },
    {
        manufacturer: "GIGABYTE",
        model: "Z590 Vision G",
        price: 179.90,
        socket: "LGA1200",
        ramSlots: 4,
        ramType: "DDR4",
        pcieSlots: 5,
        pcieRequirement: 3.0,
        sataSlots: 6,
        usbPorts: 8,
        powerRequirement: 215,
    },
    {
        manufacturer: "ASUS",
        model: "ROG Maximus Z790 Apex",
        price: 179.56,
        socket: "LGA1700",
        ramSlots: 2,
        ramType: "DDR5",
        pcieSlots: 4,
        pcieRequirement: 4.0,
        sataSlots: 4,
        usbPorts: 8,
        powerRequirement: 135,
    },
    {
        manufacturer: "MSI",
        model: "MEG Z690 Unify-X",
        price: 174.90,
        socket: "LGA1700",
        ramSlots: 2,
        ramType: "DDR5",
        pcieSlots: 6,
        pcieRequirement: 4.0,
        sataSlots: 4,
        usbPorts: 9,
        powerRequirement: 235,
    },
]

